### ISSUE TITLE
<Pre> Elements Lack Horizontal Scrolling 

### ISSUE THREAD

**Issue by lukejeremy** [jedfoster/Roughdraft#54]
I have a [gist](https://gist.github.com/lukejeremy/725f3240ec7a2f2b6bc9) that displays as I intend it to on *gist.github.com*. However, that [gist on roughdraft](http://lukejeremy.roughdraft.io/725f3240ec7a2f2b6bc9-git-init-vs-git-init-bare) looks broken. The code section wraps and destroys my ASCII graph. 

Granted, the Github code section is just wider in this case. However, in general code sections on *gist.github.com* scroll horizontally for [wide content](https://gist.github.com/lukejeremy/54335aa7cd25715e3602). I think `<pre>` element horizontal scrolling would make more sense than wrapping on Roughdraft because:

 * I use code sections to display something exactly as I type it; and  
 * scrolling would be more consistent with *gist.github.com*; 
       * i.e. I wouldn't have to ask myself "How will this look on Roughdraft?"

I was able to add horizontal scrolling in *Chrome 40.0.2214.94 (64-bit)* by changing the following at line 77 of *style.css*

```css
pre {
  white-space: pre-wrap;
  word-wrap: break-word;
  }
```

to this:

```css
pre {
  /* white-space: pre-wrap; */
  /* word-wrap: break-word; */
  overflow:  auto;
}
```

I have not investigated what other side-effects this change could have. However, I think this could be a simple change that will improve Roughdraft. :thumbsup:
